// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtcmDQLVqm04UDJQIPwBu4jylL39vjnss',
    appId: '1:297501466821:web:a9ea3a0600bf155c7b50ac',
    messagingSenderId: '297501466821',
    projectId: 'assignmentgroceryproject',
    authDomain: 'assignmentgroceryproject.firebaseapp.com',
    databaseURL: 'https://assignmentgroceryproject-default-rtdb.firebaseio.com',
    storageBucket: 'assignmentgroceryproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKTxXp5aqVMcKbNWpS5vs6qF6RDyB5Dhw',
    appId: '1:297501466821:android:a3cd97291f48e5a77b50ac',
    messagingSenderId: '297501466821',
    projectId: 'assignmentgroceryproject',
    databaseURL: 'https://assignmentgroceryproject-default-rtdb.firebaseio.com',
    storageBucket: 'assignmentgroceryproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3YlSx7EyEnzmdj6vY6tJKlqlVlvHPTe4',
    appId: '1:297501466821:ios:5f46420f189968247b50ac',
    messagingSenderId: '297501466821',
    projectId: 'assignmentgroceryproject',
    databaseURL: 'https://assignmentgroceryproject-default-rtdb.firebaseio.com',
    storageBucket: 'assignmentgroceryproject.appspot.com',
    iosBundleId: 'com.example.grocery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3YlSx7EyEnzmdj6vY6tJKlqlVlvHPTe4',
    appId: '1:297501466821:ios:5f46420f189968247b50ac',
    messagingSenderId: '297501466821',
    projectId: 'assignmentgroceryproject',
    databaseURL: 'https://assignmentgroceryproject-default-rtdb.firebaseio.com',
    storageBucket: 'assignmentgroceryproject.appspot.com',
    iosBundleId: 'com.example.grocery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtcmDQLVqm04UDJQIPwBu4jylL39vjnss',
    appId: '1:297501466821:web:10a06e05545e9c7d7b50ac',
    messagingSenderId: '297501466821',
    projectId: 'assignmentgroceryproject',
    authDomain: 'assignmentgroceryproject.firebaseapp.com',
    databaseURL: 'https://assignmentgroceryproject-default-rtdb.firebaseio.com',
    storageBucket: 'assignmentgroceryproject.appspot.com',
  );
}
